export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

export const GET_COUNTER_REQUEST = 'GET_COUNTER/REQUEST';
export const GET_COUNTER_FAILURE = 'GET_COUNTER/FAILURE';
export const GET_COUNTER_SUCCESS = 'GET_COUNTER/SUCCESS';
